proyecto1/clientes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.auth import views as auth_views

app_name = "clientes_app"

urlpatterns = [
    path('',views.Home.as_view(), name='home'),
    path('compras/',views.compras.as_view(), name='compras'),
    path('login/',auth_views.LoginView.as_view(template_name="crud/login.html"), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name="crud/login.html"), name='logout'),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)#Carga imagenes

proyecto1/persona/urls.py
from django.urls import path
from . import views

app_name = "personal_app"


urlpatterns = [
    path('',views.Inicio.as_view(), name='inicio'),
    path('lista/',views.Lista.as_view(), name='lista'),
    path('crear/',views.Crear.as_view(), name='crear'),
    path('editar/<pk>',views.Editar.as_view(), name='editar'),
    path('eliminar/<pk>',views.Eliminar.as_view(), name='eliminar'),
    
]#urls 

proyecto1/proyecto1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('clientes.urls')),
    path('personal/',include('persona.urls'))
]

proyecto1/clientes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class DatosBase(models.Model):
    estado = models.BooleanField(default=True)
    fecha_registro = models.DateField(auto_now_add=True)
    fecha_modificacion = models.DateField(auto_now=True)
    usuario = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE) #Este usuario es creado por django


    class Meta:
        abstract =True
        

proyecto1/persona/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User #Para saber cual es el usuario hizo el cambio
# Create your models here.
from clientes.models import DatosBase

class Area(DatosBase):
    nom_Area=models.CharField(max_length=100, verbose_name ='Area', null= False, blank=False)
    

    def __str__(self):
        fila = self.nom_Area
        return fila
    
class Estudios(DatosBase):
    nom_Estudios=models.CharField( max_length=100, blank=False, null = False)

    def __str__(self):
        fila = self.nom_Estudios
        return fila

carrera = (  #Choices para escojer el tipo de carrera
    ('sistemas','sistemas'),
    ('TICs','TICs'),
    ('Sofware','Sofware'),
    ('Ciencias de la computacion','Ciencias de la computacion'),
    ('Programador','Programador')
)

class Personal(DatosBase):#Extiende
    nom = models.CharField(max_length=50, verbose_name='Nombre', blank= False, null= False)
    ap = models.CharField(max_length=50, verbose_name='Apellido Materno', blank= False, null= False)
    am = models.CharField(max_length=50, verbose_name='Apellido Paterno', blank= False, null= False)
    foto = models.ImageField(upload_to='imagenes/', verbose_name='Foto',blank=True, null=True)#Campo para la foto
    area = models.ForeignKey(Area, verbose_name='Area', on_delete= models.CASCADE)
    estudios = models.ForeignKey(Estudios, verbose_name='Estudios', on_delete= models.CASCADE)
    carrera = models.CharField(max_length=30,verbose_name='Carrera',choices=carrera)

    def __str__(self):
        fila = str(self.id) + '-' + self.nom + '-' + self.ap
        return fila
    
    def delete(self, using=None, keep_parents=False):
        self.foto.storage.delete(self.foto.name)
        super().delete()
    
#Agregando Modelos

proyecto1/persona/forms.py
from dataclasses import fields
from socket import fromshare
from django import forms 
from .models import *

class Personalform(forms.ModelForm):

    class Meta:
        model = Personal
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(Personalform, self).__init__(*args, **kwargs)
        self.fields['area'].empty_label="Selecciona"
        self.fields['estudios'].empty_label="Selecciona"
        self.fields['carrera'].empty_label="Selecciona"
        self.fields['carrera'].choices =[("","Selecciona"),] + list(self.fields["carrera"].choices)[1:]
        self.fields['ap'].required=True
        #self.fields['am'].required=False
        #Este es el formulario para los campos

proyecto1/clientes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import *
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class Home(LoginRequiredMixin,TemplateView):
    template_name='crud/home.html'
    login_url ='clientes_app/login'


class compras(LoginRequiredMixin,TemplateView):
    template_name='crud/compras.html'
    login_url ='clientes_app:login'

class loginView(LoginRequiredMixin,TemplateView):
    template_name='crud/login.html'
    login_url ='clientes_app:login'



    

proyecto1/persona/views.py
from django.shortcuts import render
from .models import Personal
from .forms import Personalform
from django.urls import reverse_lazy, reverse

from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView

# Create your views here.
class Inicio(TemplateView):
    template_name = 'paginas_base/inicio.html'
    
class Lista(ListView):
    template_name = 'crud/lista.html'
    model = Personal
    ordering = '-id' # ordenar desendiente
    queryset = Personal.objects.all()
    context_object_name = 'Personas' #obtener el nombre personas
#%$

class Crear(CreateView):
    template_name = 'crud/crear.html'
    model = Personal
    form_class = Personalform

    def get_success_url(self, **kwargs):
        return reverse("personal_app:lista")

class Editar(UpdateView):
    template_name = 'crud/editar.html'#Platilla para el crud 
    model = Personal 
    form_class = Personalform
    pk_url_kwarg= 'pk'

    def get_success_url(self,**kwargs):
        return reverse('personal_app:lista')
    
class Eliminar(DeleteView):#Clase de eliminar por pk
    template_name = "crud/eliminar.html"
    model =Personal
    pk_url_kwarg ='pk' #Elimina mediante le pk

    def get_success_url(self,**kwargs):
        return reverse('personal_app:lista') #Redirigir la aplicacion

proyecto1/clientes/templates/crud/compras.html
{% extends 'base/base.html'%}

{% block title %} Compras {% endblock title%}

{% block titulo_izq%}
<div class="sidebar-brand-text mx-3"> Principal<sup>2</sup></div>
{% endblock titulo_izq%}

{% block body %}
Esto es el contenido de la pagina principal
{% endblock body %}

{% block footer %}
holaa
{% endblock footer%}

proyecto1/clientes/templates/crud/home.html
{%  extends 'base/base.html' %}

proyecto1/clientes/templates/crud/login.html
{% extends 'base/base.html'%}

{% block title %} Login {% endblock title%}

{% block login %}
<div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

        <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        <div class="col-lg-6">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user" method = 'POST'> {% csrf_token %}
                                    <div class="form-group">
                                        <input type="text" class="form-control form-control-user"
                                            name= 'username' id="id_username" aria-describedby="emailHelp"
                                            placeholder="Nombre">
                                    </div>
                                    <div class="form-group">
                                        <input type="password" class="form-control form-control-user"
                                           name = 'password' id="id_password" placeholder="Password">
                                    </div>
                                    
                                    <button type = 'submit' class="btn btn-primary btn-user btn-block">
                                        Login
                                    </button>
                                    
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="register.html">Create an Account!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock login %}

{% block sidebar %}

{% endblock sidebar%}

{%block topbar %}

{% endblock topbar%}

{% block body %}
{% endblock body %}

{% block footer1 %}

{% endblock footer1%}

proyecto1/persona/templates/crud/editar.html
{%  extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %} Editar Pesona {% endblock titulo%}
{% block body %}
<div class="card">
    <div class="card-header">
        Editar Persona
    </div>
    <div class="card-body">
        <h4 class="card-title">Editar Persona</h4>
        <form action ="" method="post" enctype= "multipart/form-data" autocomplete="off">
            {% csrf_token %}
            
            {{form.nom }}
            {{form.ap }}
            {{form.am }}
            {{form.estado}}
            <br>
            {% if form.foto.value %}
            <img src="{{MEDIA_URL}}/imagenes/{{form.foto.value}}" alt="" width="80">
            {% endif %}
            {{form.foto}}
            <br>
            <br>
            {{form.area}}
            <br>
            {{form.estudios}}
            <br>
            {{form.carrera}}
            <br>
            {{form.usuario}}
                        
            <br>
            <br>
            <input name="btn-guardar" id="btn_guardar" class="btn btn-success" type="submit" value="Guardar">
            <a name="btnCancelar" id="btnCancelar" class="btn btn-primary" href="{% url 'personal_app:lista' %}" role="button">Cancelar </a>
        </form>
    </div>
</div>
                    


{% endblock body %}

proyecto1/persona/templates/crud/eliminar.html
{%  extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block titulo %} Agregando Pesona {% endblock titulo%}
{% block body %}

<h4 class="card-title"> Persona </4>
    <p>Seguro desea eliminar</p>
    <form  method="post" id="fr-eliminar" autocomplete="off">
        {% csrf_token %}
        <button name="btn-guardar" id="btn_guardar" class="btn btn-danger" type="submit"> Guardar </button>
        <a name="btnCancelar" id="btnCancelar" class="btn btn-primary" href="{% url 'personal_app:lista' %}" role="button">Eliminar</a>
    </form>

{% endblock body %}

proyecto1/persona/templates/crud/lista.html
{% extends "base/base.html" %}

{% block titulo %}Listado de Personal {% endblock titulo %}
{% block body %}
    <div class="card">
        <div class="card-header">
            <a name="btnuevo" id="btnuevo" class="btn btn-primary" href="{% url 'personal_app:crear'%}" role="button">Agregar Nueva Persona</a>
        </div>
        <div class="card-body">
            <h4 class="card-title">Persona</h4>
            <table class="table datatables">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Ap</th>
                        <th>Am</th>                       
                        <th>Area</th>
                        <th>Estudios</th>
                        <th>Carrera</th>
                        <th>Foto</th>
                        <th>Estado</th>
                        <th>Modificación</th> 
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {%  for ps in Personas %}
                        {% if ps.estado == True %}
                            <tr>
                                <td>{{ ps.id }}</td>
                                <td>{{ ps.nom }}</td>
                                <td>{{ ps.ap }}</td>
                                <td>{{ ps.am }}</td>
                                <td>{{ ps.area }}</td>
                                <td>{{ ps.estudios }}</td>
                                <td>{{ ps.carrera }}</td>                               
                                {% if ps.foto.url %}
                                    <td>
                                    <img src="{{ ps.foto.url }}" height="60">
                                    </td>
                                {% else %}
                                    <td>Sin</td>
                                {% endif %}
                                <td>{{ ps.estado }}</td>
                                <td>{{ ps.fecha_modificacion|date:"d/m/y"}} 
                                <td>
                                <a name="bteditar" id="bteditar" class="btn btn-info" href="{% url 'personal_app:editar' ps.id %}" role="button">Editar</a>
                                <a name="bteliminar" id="bteliminar" class="btn btn-danger" href="{% url 'personal_app:eliminar' ps.id%}" role="button">Eliminar</a>
                            </td>                        
                        </tr>
                            {% endif %}
                           
                        {% endfor %}
                      
                        
                </tbody>
            </table>
            
            
        </div>
        <div class="card-footer text-muted">
        
        </div>
    </div>
   
   

{% endblock body %}

{% block Datatables %}
<script>
    $(document).ready(function () {
        $('.datatables').DataTable();
    });
</script>
{% endblock Datatables %}

proyecto1/persona/templates/paginas_base/inicio.html
{% extends "base/base.html" %}
{% block titulo %}
Personal Inicio
{% endblock titulo%}

{% block body %}
<div class="p-5 mb-4 bg-ligth rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold"> Bienvenido al sistema</h1>
        <p class="col-md-8 fs-4"> Seccion Personal</p>
        <a name="" id="" class="btn btn-primary btn-lg" href="#" role="button">Listado de Personal</a>
    </div> 
    
  </div>
{% endblock body %}

{% block footer%}

{% endblock footer%}